language: php
php:
- '7.2'
services:
- docker
install: composer install
before_deploy: npm install; node dev/extractScriptPath.js > dev/paths.js; npm run
  production; zip --exclude=node_modules/* --exclude=*.DS_Store*  --exclude=*.git*  --exclude=vendor/*
  --exclude=sass/* --exclude=\.sass-cache/* --exclude=/dev/* --exclude=/test/* -r
  zipfile.zip .
deploy:
- provider: elasticbeanstalk
  access_key_id: AKIAZ7YCWSRWTJPZXWWI
  secret_access_key:
    secure: Kkr+Qx+1KFsVKOkUXY6VKJBZRhJCDFUlDETMmK60juHQS2pKZdRORhpGWViktyQweEE6P9MD8NaSHnwg6KAJS+ltjadbDM6u5tzk2/+okQnagMJlu5rCA5XAd8yOXAJYZv0GlPNgDa+WL4nRtmmQHa12nOxpPjU4wspJv7SCp7HNs/f5765DrmOP8U9dg2QeMNbtlK6S0fKs8gmv6RqiuKS4KuxqKv97RviWJAM99p/CPbpJyePD8dXCmXwSgeU6HSt5ekO3i2FCpgBu3cZ7q3hVps5ua1SyTJUs8Sm+meKbuiEy/QWRkJwjtVVkrKriIw2Md75lXHrnG5v+m6g1xdzAUvXB9e8LSnryTvZGHoseEnHTqA2kfGMwmC7ggKXiTEbuPiIPevWVjGnZcUil1gZv3bNAisJ/hweuDV+hR6v2KB0o4VFLCk2VB1fdRmy3XtNNQWc31u7KOeJv7AnGRdkOEmh8JRdTjXLdrCTgd0/4UfrAfRjlezpt6gNMiBIEhoA/rwTw7jUxqpLx9X1Tpxkq9RbmDiwZMWc7hcagj5iwhpd8O4/T2eBGIkUU516MieVX34KUMhXObgnn09qgpPtx5BWK7O5+YnnLlL/BwmZIDhbV1QCCWu221xfhFqvp4w5ExbuqI1hocdGb8c/KsPzZrsmKFVe9qqDRoowJtSk=
  region: us-east-1
  app: sugarcap.com
  env: Sugarcapcom-env
  bucket_name: sugarcap-ops
  bucket_path: travis
  skip_cleanup: true
  zip_file: zipfile.zip
  on:
    repo: SugarCapital/sugarcap.com
    branch: master
